=== a2geek/ghost-assembler/api/src/main/resources/schemas/cpu-definition-3.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://a2geek/schemas/cpu-definition/3.0" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://a2geek/schemas/cpu-definition/3.0" version="1.0">
      
  
  <xs:element name="definition" type="tns:DefinitionType"/>
      
  
  <xs:complexType abstract="true" name="AddressModeType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Base class for addressing modes.

(author): Rob
(see): AddressModeDefinition, AddressModeReference]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence/>
            
    
    <xs:attribute name="id" type="xs:ID" use="required"/>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="AddressModeDefinitionType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Container for information regarding the CPU addressing mode.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:complexContent>
                  
      
      <xs:extension base="tns:AddressModeType">
                        
        
        <xs:sequence>
                              
          
          <xs:element minOccurs="0" name="title" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="description" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="mnemonic-format" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="format" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="regex" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="pattern" type="xs:string"/>
                              
          
          <xs:element minOccurs="0" name="constraint" type="xs:string"/>
                              
          
          <xs:element name="code">
                                    
            
            <xs:complexType>
                                          
              
              <xs:sequence>
                                                
                
                <xs:element maxOccurs="unbounded" name="byte" type="tns:ByteCodeType"/>
                                              
              
              </xs:sequence>
                                        
            
            </xs:complexType>
                                  
          
          </xs:element>
                            
        
        </xs:sequence>
                      
      
      </xs:extension>
                
    
    </xs:complexContent>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="ByteCodeType">
            
    
    <xs:simpleContent>
                  
      
      <xs:extension base="xs:string">
                        
        
        <xs:attribute name="mnemonic-match" type="xs:string"/>
                      
      
      </xs:extension>
                
    
    </xs:simpleContent>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="AddressModeReferenceType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[This is a place-holder which we presume will be inherited from another CPU definition.
If the reference is not inherited, that implies a structural error in the definition.
Within the XML file, the reference serves as a contract that the addressing mode
will be defined.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:complexContent>
                  
      
      <xs:extension base="tns:AddressModeType">
                        
        
        <xs:sequence/>
                      
      
      </xs:extension>
                
    
    </xs:complexContent>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="AddressSpaceType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Definition of the address space available for the defined CPU.
This includes the memory size (defined in bits) as well as any
intrinsic memory locations for the CPU.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element maxOccurs="unbounded" minOccurs="0" name="memory-location" type="tns:MemoryLocationType"/>
                
    
    </xs:sequence>
            
    
    <xs:attribute name="bit-size" type="xs:int" use="required"/>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="MemoryLocationType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[A memory location.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element name="name" type="xs:string"/>
                  
      
      <xs:element name="address" type="xs:string"/>
                
    
    </xs:sequence>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="DefinitionType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[A CPU definition.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element name="name" type="xs:string"/>
                  
      
      <xs:element minOccurs="0" name="overview" type="tns:OverviewType"/>
                  
      
      <xs:element minOccurs="0" name="output-format" type="tns:OutputFormatType"/>
                  
      
      <xs:element name="address-space" type="tns:AddressSpaceType"/>
                  
      
      <xs:element minOccurs="0" name="registers">
                        
        
        <xs:complexType>
                              
          
          <xs:sequence>
                                    
            
            <xs:element maxOccurs="unbounded" name="register" type="tns:RegisterType"/>
                                  
          
          </xs:sequence>
                            
        
        </xs:complexType>
                      
      
      </xs:element>
                  
      
      <xs:element name="address-modes">
                        
        
        <xs:complexType>
                              
          
          <xs:sequence>
                                    
            
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                                          
              
              <xs:element name="address-mode" type="tns:AddressModeDefinitionType"/>
                                          
              
              <xs:element name="address-mode-reference" type="tns:AddressModeReferenceType"/>
                                        
            
            </xs:choice>
                                  
          
          </xs:sequence>
                            
        
        </xs:complexType>
                      
      
      </xs:element>
                  
      
      <xs:element name="operations">
                        
        
        <xs:complexType>
                              
          
          <xs:sequence>
                                    
            
            <xs:element maxOccurs="unbounded" name="operation" type="tns:OperationType"/>
                                  
          
          </xs:sequence>
                            
        
        </xs:complexType>
                      
      
      </xs:element>
                
    
    </xs:sequence>
            
    
    <xs:attribute name="inherit-from" type="xs:string"/>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="OverviewType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Overview of the CPU definition.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:simpleContent>
                  
      
      <xs:extension base="xs:string">
                        
        
        <xs:attribute name="href" type="xs:anyURI"/>
                      
      
      </xs:extension>
                
    
    </xs:simpleContent>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="OutputFormatType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Defines any output specifics of the assembled file.
This may include magic bytes required by the CPU or interpreter.
Usage is expected to be rare.
<p>
NOTE: This is *NOT* an operating-system or file-system type container!!

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element minOccurs="0" name="header">
                        
        
        <xs:complexType>
                              
          
          <xs:sequence>
                                    
            
            <xs:element maxOccurs="unbounded" minOccurs="0" name="byte" type="xs:string"/>
                                  
          
          </xs:sequence>
                            
        
        </xs:complexType>
                      
      
      </xs:element>
                
    
    </xs:sequence>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="RegisterType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Definition of a CPU register.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element name="name" type="xs:string"/>
                  
      
      <xs:element minOccurs="0" name="description" type="xs:string"/>
                
    
    </xs:sequence>
            
    
    <xs:attribute name="id" type="xs:ID" use="required"/>
            
    
    <xs:attribute name="bit-size" type="xs:short" use="required"/>
            
    
    <xs:attribute name="value" type="xs:string"/>
            
    
    <xs:attribute name="groups" type="xs:string"/>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="OperationType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[An individual operation.
<p>
Note:  (of historical importance)
We store opcodes by addressModeId instead of object because inheritance causes 
issues with object relations.  (If parent and child share an addressing mode,
and they each have an AddressMode object, which one is to be used?  How about
back-patching the appropriate instance of AddressMode?  Etc.)

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence>
                  
      
      <xs:element name="mnemonic" type="xs:string"/>
                  
      
      <xs:element minOccurs="0" name="description" type="xs:string"/>
                  
      
      <xs:element maxOccurs="unbounded" minOccurs="0" name="addressing-mode" type="tns:OperationAddressingType"/>
                
    
    </xs:sequence>
          
  
  </xs:complexType>
      
  
  <xs:complexType name="OperationAddressingType">
        
    <xs:annotation>
            
      <xs:documentation><![CDATA[Operation addressing represents one of potentially many addressing
modes that an operation will support.

(author): Rob]]></xs:documentation>
          
    </xs:annotation>
            
    
    <xs:sequence/>
            
    
    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
            
    
    <xs:attribute name="opcode" type="xs:string" use="required"/>
          
  
  </xs:complexType>
      
  
  <xs:simpleType name="mnemonicMatchType">
            
    
    <xs:restriction base="xs:string">
                  
      
      <xs:enumeration value="DIRECT_MATCH"/>
                  
      
      <xs:enumeration value="PATTERN_MATCH"/>
                
    
    </xs:restriction>
          
  
  </xs:simpleType>
    

</xs:schema>

=== a2geek/ghost-assembler/api/src/main/resources/definitions/WDC65C02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Definition for the WDC 65C02.
 -->
<definition xmlns="https://a2geek/schemas/cpu-definition/3.0"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="https://a2geek/schemas/cpu-definition/3.0 ../schemas/cpu-definition-3.0.xsd"
			inherit-from="MOS6502">
	
	<name>WDC65C02</name>
	<overview href="http://en.wikipedia.org/wiki/65C02">
	The WDC 65C02 8-bit CPU is an upgraded CMOS version of the popular MOS Technology 6502 
	microprocessor, the redesign being made by Bill Mensch of the Western Design Center (WDC). 
	The 65C02 was second-sourced by NCR, GTE, Rockwell, Synertek and Sanyo.
	</overview>
	
	<address-space bit-size="16" />
	
	<address-modes>
		<address-mode id="zero-page-indirect">
			<title>Zero Page Indirect</title>
			<description>
				With Zero Page Indirect addressing mode, the second byte of the
				instruction is a zero page indirect address that points to the low byte of
				a two byte effective address.
			</description>
			<format>(zp)</format>
			<regex>\(([:expr:]+)\)</regex>
			<pattern>(?)</pattern>
			<constraint>zp &lt;= 0xff &amp;&amp; zp &gt;= 0x00</constraint>
			<code>
				<byte>opcode</byte>
				<byte>zp</byte>
			</code>
		</address-mode>
		<address-mode id="absolute-indexed-indirect-x">
			<title>Absolute Indexed Indirect</title>
			<description>
				With the Absolute Indexed Indirect addressing mode, the X Index Register
				is added to the second and third byes of the instruction to form an
				address to a pointer. This address mode is only used with the JMP
				instruction and the program Counter is loaded with the first and second
				bytes at this pointer.
			</description>
			<format>(addr,X)</format>
			<regex>\(([:expr:]+),x\)</regex>
			<pattern>(?,x)</pattern>
			<code>
				<byte>opcode</byte>
				<byte>addr</byte>
				<byte>addr>>8</byte>
			</code>
		</address-mode>
		<!-- Defined in "MOS6502". -->
		<address-mode-reference id="accumulator" />
		<address-mode-reference id="absolute" />
		<address-mode-reference id="absolute-indexed-x" />
		<address-mode-reference id="immediate" />
		<address-mode-reference id="implied" />
		<address-mode-reference id="relative" />
		<address-mode-reference id="zero-page" />
		<address-mode-reference id="zero-page-indexed-x" />
	</address-modes>

	<operations>
		<operation>
			<mnemonic>ADC</mnemonic>
			<description>Add with carry</description>
			<addressing-mode ref="zero-page-indirect" opcode="0x72" />
		</operation>

		<operation>
			<mnemonic>AND</mnemonic>
			<description>Bit-wise and accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0x32" />
		</operation>

		<operation>
			<mnemonic>BIT</mnemonic>
			<description>Bit test</description>
			<addressing-mode ref="immediate" opcode="0x89" />
			<addressing-mode ref="zero-page-indexed-x" opcode="0x34" />
			<addressing-mode ref="absolute-indexed-x" opcode="0x3c" />
		</operation>

		<operation>
			<mnemonic>BRA</mnemonic>
			<description>Branch always</description>
			<addressing-mode ref="relative" opcode="0x80" />
		</operation>

		<operation>
			<mnemonic>CMP</mnemonic>
			<description>Compare accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0xd2" />
		</operation>

		<operation>
			<mnemonic>DEC</mnemonic>
			<description>Decrement accumulator</description>
			<addressing-mode ref="accumulator" opcode="0x3a" />
		</operation>

		<operation>
			<mnemonic>EOR</mnemonic>
			<description>Bit-wise exclusive-or accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0x52" />
		</operation>

		<operation>
			<mnemonic>INC</mnemonic>
			<description>Increment accumulator</description>
			<addressing-mode ref="accumulator" opcode="0x1a" />
		</operation>

		<operation>
			<mnemonic>JMP</mnemonic>
			<description>Jump to address</description>
			<addressing-mode ref="absolute-indexed-indirect-x" opcode="0x7c" />
		</operation>

		<operation>
			<mnemonic>LDA</mnemonic>
			<description>Load accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0xb2" />
		</operation>

		<operation>
			<mnemonic>ORA</mnemonic>
			<description>Bit-wise or accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0x12" />
		</operation>

		<operation>
			<mnemonic>PHX</mnemonic>
			<description>Push X register on to stack</description>
			<addressing-mode ref="implied" opcode="0xda" />
		</operation>

		<operation>
			<mnemonic>PHY</mnemonic>
			<description>Push Y register on to stack</description>
			<addressing-mode ref="implied" opcode="0x5a" />
		</operation>

		<operation>
			<mnemonic>PLX</mnemonic>
			<description>Pull X register off of stack</description>
			<addressing-mode ref="implied" opcode="0xfa" />
		</operation>

		<operation>
			<mnemonic>PLY</mnemonic>
			<description>Pull Y register off of stack</description>
			<addressing-mode ref="implied" opcode="0x7a" />
		</operation>

		<operation>
			<mnemonic>SBC</mnemonic>
			<description>Subtract with carry</description>
			<addressing-mode ref="zero-page-indirect" opcode="0xf2" />
		</operation>

		<operation>
			<mnemonic>STA</mnemonic>
			<description>Store accumulator</description>
			<addressing-mode ref="zero-page-indirect" opcode="0x92" />
		</operation>

		<operation>
			<mnemonic>STZ</mnemonic>
			<description>Store zero</description>
			<addressing-mode ref="zero-page" opcode="0x64" />
			<addressing-mode ref="absolute" opcode="0x9c" />
			<addressing-mode ref="zero-page-indexed-x" opcode="0x74" />
			<addressing-mode ref="absolute-indexed-x" opcode="0x9e" />
		</operation>

		<operation>
			<mnemonic>TRB</mnemonic>
			<description>Test and reset bit</description>
			<addressing-mode ref="zero-page" opcode="0x14" />
			<addressing-mode ref="absolute" opcode="0x1c" />
		</operation>

		<operation>
			<mnemonic>TSB</mnemonic>
			<description>Test and set bit</description>
			<addressing-mode ref="zero-page" opcode="0x04" />
			<addressing-mode ref="absolute" opcode="0x0c" />
		</operation>
	</operations>
</definition>

=== a2geek/ghost-assembler/api/src/test/resources/Test-1 CPU.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="https://a2geek/schemas/cpu-definition/3.0"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="https://a2geek/schemas/cpu-definition/3.0 ../../main/resources/schemas/cpu-definition-3.0.xsd">

	<name>Test-1 CPU</name>
	<overview>
		This CPU is used by the LineAssemblerServiceTest class.
	</overview>

	<address-space bit-size="16" />

	<registers>
		<register id="R1" bit-size="16" groups="Rn" value="0x1">
			<name>R1</name>
		</register>
	</registers>

	<address-modes>
		<address-mode id="absolute-into-A">
			<format>A,[addr]</format>
			<regex>A,\[(.+)\]</regex>
			<pattern>A,[?]</pattern>
			<code>
				<byte>opcode</byte>
				<byte>addr>>8</byte>
				<byte>addr</byte>
			</code>
		</address-mode>
		<address-mode id="fake-register">
			<format>Rn,value</format>
			<regex>([rR].+),(.+)</regex>
			<pattern>{R?},?</pattern>
			<code>
				<byte>opcode | Rn</byte>
				<byte>value>>8</byte>
				<byte>value</byte>
			</code>
		</address-mode>
		<address-mode id="absolute-address">
			<format>addr</format>
			<regex>(.+)</regex>
			<pattern>?</pattern>
			<code>
				<byte>opcode</byte>
				<byte>addr>>8</byte>
				<byte>addr</byte>
			</code>
		</address-mode>
		<address-mode id="none">
			<code>
				<byte>opcode</byte>
			</code>
		</address-mode>
	</address-modes>

	<operations>
		<operation>
			<mnemonic>HLT</mnemonic>
			<addressing-mode ref="none" opcode="0xff"/>
		</operation>
		<operation>
			<mnemonic>JMP</mnemonic>
			<addressing-mode ref="absolute-address" opcode="0x30"/>
		</operation>
		<operation>
			<mnemonic>JZ</mnemonic>
			<addressing-mode ref="absolute-address" opcode="0x31"/>
		</operation>
		<operation>
			<mnemonic>LOD</mnemonic>
			<addressing-mode ref="absolute-into-A" opcode="0x10"/>
		</operation>
		<operation>
			<mnemonic>LDR</mnemonic>
			<addressing-mode ref="fake-register" opcode="0x80"/>
		</operation>
	</operations>
	
</definition>

=== a2geek/ghost-assembler/api/src/main/resources/definitions/SWEET16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Definition for SWEET-16 "CPU" as defined by Steve Wozniak.
 -->
<definition xmlns="https://a2geek/schemas/cpu-definition/3.0"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="https://a2geek/schemas/cpu-definition/3.0 ../schemas/cpu-definition-3.0.xsd">

	<name>Sweet 16 CPU</name>
	<overview href="http://en.wikipedia.org/wiki/SWEET16">
		SWEET16 is an interpreted "byte-code" language invented by Steve Wozniak and implemented
		as part of the Integer BASIC ROM in the Apple II computer. It was created because Wozniak
		needed to manipulate 16-bit pointer data in his implementation of BASIC, and the Apple II
		was an 8-bit computer.

		SWEET16 code is executed as if it were running on a (non-existent) 16-bit processor with
		sixteen, internal 16-bit little-endian registers, R0 through R15. Some registers have
		well-defined functions:

		* R0 is the accumulator.
		* R14 is the status register.
		* R13 stores the result of all comparison operations for branch testing.
		* R15 is the program counter.

		The 16 virtual registers, 32 bytes in total, are located in the zero page of the
		Apple II's real, physical memory map (at $00-$1F). The actual SWEET16 interpreter is
		located from $F689 to $F7FC.

		According to Wozniak, the SWEET16 implementation is a model of frugal coding, taking
		up only about 300 bytes in memory. SWEET16 runs about 10 times slower than the equivalent
		native 6502 code.
	</overview>

	<address-space bit-size="16"/>

	<registers>
		<register id="R0" bit-size="16" value="0" groups="Rn">
			<name>SWEET 16 accumulator</name>
		</register>
		<register id="R1" bit-size="16" value="1" groups="Rn">
			<name>Register R1</name>
		</register>
		<register id="R2" bit-size="16" value="2" groups="Rn">
			<name>Register R3</name>
		</register>
		<register id="R3" bit-size="16" value="3" groups="Rn">
			<name>Register R3</name>
		</register>
		<register id="R4" bit-size="16" value="4" groups="Rn">
			<name>Register R4</name>
		</register>
		<register id="R5" bit-size="16" value="5" groups="Rn">
			<name>Register R5</name>
		</register>
		<register id="R6" bit-size="16" value="6" groups="Rn">
			<name>Register R6</name>
		</register>
		<register id="R7" bit-size="16" value="7" groups="Rn">
			<name>Register R7</name>
		</register>
		<register id="R8" bit-size="16" value="8" groups="Rn">
			<name>Register R8</name>
		</register>
		<register id="R9" bit-size="16" value="9" groups="Rn">
			<name>Register R9</name>
		</register>
		<register id="R10" bit-size="16" value="10" groups="Rn">
			<name>Register R10</name>
		</register>
		<register id="R11" bit-size="16" value="11" groups="Rn">
			<name>Register R11</name>
		</register>
		<register id="R12" bit-size="16" value="12" groups="Rn">
			<name>Subroutine return stack pointer</name>
		</register>
		<register id="R13" bit-size="16" value="13" groups="Rn">
			<name>Compare instruction results</name>
		</register>
		<register id="R14" bit-size="16" value="14" groups="Rn">
			<name>Status register</name>
		</register>
		<register id="R15" bit-size="16" value="15" groups="Rn">
			<name>Program counter (PC)</name>
		</register>
	</registers>

	<address-modes>
		<address-mode id="register-immediate">
			<format>Rn,value</format>
			<regex>([rR].+),(.+)</regex>
			<pattern>{R?},?</pattern>
			<code>
				<byte>(opcode&amp;0xf0) | (Rn&amp;0x0f)</byte>
				<byte>value</byte>
				<byte>value>>8</byte>
			</code>
		</address-mode>
		<address-mode id="register-indirect">
			<format>@Rn</format>
			<regex>@([Rr].+)</regex>
			<pattern>@{R?}</pattern>
			<code>
				<byte>(opcode&amp;0xf0) | (Rn&amp;0x0f)</byte>
			</code>
		</address-mode>
		<address-mode id="register-direct">
			<format>Rn</format>
			<regex>([Rr].+)</regex>
			<pattern>{R?}</pattern>
			<code>
				<byte>(opcode&amp;0xf0) | (Rn&amp;0x0f)</byte>
			</code>
		</address-mode>
		<address-mode id="relative-branch">
			<format>addr</format>
			<regex>(.+)</regex>
			<pattern>?</pattern>
			<code>
				<byte>opcode</byte>
				<byte>addr - PC - 2</byte>
			</code>
		</address-mode>
		<address-mode id="none">
			<code>
				<byte>opcode</byte>
			</code>
		</address-mode>
	</address-modes>

	<operations>
		<operation>
			<mnemonic>SET</mnemonic>
			<description>Set constant</description>
			<addressing-mode ref="register-immediate" opcode="0x10"/>
		</operation>
		<operation>
			<mnemonic>LD</mnemonic>
			<description>Load</description>
			<addressing-mode ref="register-direct" opcode="0x20"/>
			<addressing-mode ref="register-indirect" opcode="0x40"/>
		</operation>
		<operation>
			<mnemonic>ST</mnemonic>
			<description>Store</description>
			<addressing-mode ref="register-direct" opcode="0x30"/>
			<addressing-mode ref="register-indirect" opcode="0x50"/>
		</operation>
		<operation>
			<mnemonic>LDD</mnemonic>
			<description>Load double indirect</description>
			<addressing-mode ref="register-indirect" opcode="0x60"/>
		</operation>
		<operation>
			<mnemonic>STD</mnemonic>
			<description>Store double indirect</description>
			<addressing-mode ref="register-indirect" opcode="0x70"/>
		</operation>
		<operation>
			<mnemonic>POP</mnemonic>
			<description>Pop indirect</description>
			<addressing-mode ref="register-indirect" opcode="0x80"/>
		</operation>
		<operation>
			<mnemonic>STP</mnemonic>
			<description>Store POP indirect</description>
			<addressing-mode ref="register-indirect" opcode="0x90"/>
		</operation>
		<operation>
			<mnemonic>ADD</mnemonic>
			<description>Add</description>
			<addressing-mode ref="register-direct" opcode="0xa0"/>
		</operation>
		<operation>
			<mnemonic>SUB</mnemonic>
			<description>Subtract</description>
			<addressing-mode ref="register-direct" opcode="0xb0"/>
		</operation>
		<operation>
			<mnemonic>POPD</mnemonic>
			<description>Pop double indirect</description>
			<addressing-mode ref="register-indirect" opcode="0xc0"/>
		</operation>
		<operation>
			<mnemonic>CPR</mnemonic>
			<description>Compare</description>
			<addressing-mode ref="register-direct" opcode="0xd0"/>
		</operation>
		<operation>
			<mnemonic>INR</mnemonic>
			<description>Increment</description>
			<addressing-mode ref="register-direct" opcode="0xe0"/>
		</operation>
		<operation>
			<mnemonic>DCR</mnemonic>
			<description>Decrement</description>
			<addressing-mode ref="register-direct" opcode="0xf0"/>
		</operation>
		<operation>
			<mnemonic>RTN</mnemonic>
			<description>Return to 6502 mode</description>
			<addressing-mode ref="none" opcode="0x00"/>
		</operation>
		<operation>
			<mnemonic>BR</mnemonic>
			<description>Branch always</description>
			<addressing-mode ref="relative-branch" opcode="0x01"/>
		</operation>
		<operation>
			<mnemonic>BNC</mnemonic>
			<description>Branch if no carry</description>
			<addressing-mode ref="relative-branch" opcode="0x02"/>
		</operation>
		<operation>
			<mnemonic>BC</mnemonic>
			<description>Branch if carry</description>
			<addressing-mode ref="relative-branch" opcode="0x03"/>
		</operation>
		<operation>
			<mnemonic>BP</mnemonic>
			<description>Branch if plus</description>
			<addressing-mode ref="relative-branch" opcode="0x04"/>
		</operation>
		<operation>
			<mnemonic>BM</mnemonic>
			<description>Branch if minus</description>
			<addressing-mode ref="relative-branch" opcode="0x05"/>
		</operation>
		<operation>
			<mnemonic>BZ</mnemonic>
			<description>Branch if zero</description>
			<addressing-mode ref="relative-branch" opcode="0x06"/>
		</operation>
		<operation>
			<mnemonic>BNZ</mnemonic>
			<description>Branch if nonzero</description>
			<addressing-mode ref="relative-branch" opcode="0x07"/>
		</operation>
		<operation>
			<mnemonic>BM1</mnemonic>
			<description>Branch if minus 1</description>
			<addressing-mode ref="relative-branch" opcode="0x08"/>
		</operation>
		<operation>
			<mnemonic>BNM1</mnemonic>
			<description>Branch if not minus 1</description>
			<addressing-mode ref="relative-branch" opcode="0x09"/>
		</operation>
		<operation>
			<mnemonic>BK</mnemonic>
			<description>Break</description>
			<addressing-mode ref="none" opcode="0x0a"/>
		</operation>
		<operation>
			<mnemonic>RS</mnemonic>
			<description>Return from subroutine</description>
			<addressing-mode ref="none" opcode="0x0b"/>
		</operation>
		<operation>
			<mnemonic>BS</mnemonic>
			<description>Branch to subroutine</description>
			<addressing-mode ref="relative-branch" opcode="0x0c"/>
		</operation>
	</operations>
	
</definition>
